apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: {{ include "wishlist.fullname" . }}-server
  name: {{ include "wishlist.fullname" . }}
spec:
  ports:
    - name: "web"
      port: 3280
      targetPort: 3280
  selector:
    app.kubernetes.io/component: {{ include "wishlist.fullname" . }}-server
